AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template deploys the Cloud Video Editing AWS Sample. **WARNING** This template
  creates Amazon EC2 Windows instance and related resources. You will be billed for
  the AWS resources used if you create a stack from this template.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - AvailabilityZones
          - VPCCIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - EditHostInstanceType
          - EditHostAccessCIDR
          - KeyPairName
      - Label:
          default: Microsoft Active Directory Configuration
        Parameters:
          - DomainDNSName
          - DomainNetBIOSName
          - DomainAdminUser
          - DomainAdminPassword
      - Label:
          default: FSX Configuration
        Parameters:
          - FileSystemSize
          - FSxThroughput
          - AZDeploymentMode
      - Label:
          default: CloudFormation Resource Location
        Parameters:
          - CloudFormationBucketName
          - CloudFormationKeyPrefix
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      DomainAdminUser:
        default: Domain Admin User
      DomainAdminPassword:
        default: Domain Admin Password
      DomainDNSName:
        default: Domain DNS Name
      DomainNetBIOSName:
        default: Domain NetBIOS Name
      EditHostAccessCIDR:
        default: Edit Host Access CIDR
      KeyPairName:
        default: Key Pair Name
      EditHostInstanceType:
        default: Amazon EC2 instance type for the video editing server
      PrivateSubnet1CIDR:
        default: Private Subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private Subnet 2 CIDR
      PublicSubnet1CIDR:
        default: Public Subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public Subnet 2 CIDR
      CloudFormationBucketName:
        default: CloudFormation S3 Bucket Name
      CloudFormationKeyPrefix:
        default: CloudFormation S3 Key Prefix
      VPCCIDR:
        default: VPC CIDR
      FileSystemSize:
        default: FSx File System Size
      FSxThroughput:
        default: FSx Throughput
      AZDeploymentMode:
        default: FSx AZ Deployment Mode

Parameters:
  AvailabilityZones:
    Description: >-
      Select 2 Availability Zones to use for the VPC subnets.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  DomainAdminUser:
    AllowedPattern: '[a-zA-Z0-9]*'
    Default: Admin
    Description: >-
      User name for the account that will be added as Domain Administrator.
      This is separate from the default "Administrator" account
    MaxLength: '25'
    MinLength: '5'
    Type: String
  DomainAdminPassword:
    AllowedPattern: (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    Description: >-
      Password for the domain admin user. Must be at least 8 characters
      containing letters, numbers and symbols
    MaxLength: '32'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DomainDNSName:
    AllowedPattern: '[a-zA-Z0-9]+\..+'
    Default: example.com
    Description: Fully qualified domain name (FQDN) of the forest root domain e.g. example.com
    MaxLength: '255'
    MinLength: '2'
    Type: String
  DomainNetBIOSName:
    AllowedPattern: '[a-zA-Z0-9]+'
    Default: example
    Description: >-
      NetBIOS name of the domain (up to 15 characters) for users of earlier
      versions of Windows e.g. EXAMPLE
    MaxLength: '15'
    MinLength: '1'
    Type: String
  EditHostAccessCIDR:
    ConstraintDescription: EditHostAccessCIDR parameter must be in the form x.x.x.x/FIXME
    Description: CIDR block to control access to the Edit Host
    Type: String
  EditHostInstanceType:
    Description: Amazon EC2 instance type for the Video Editing Servers
    Type: String
    Default: g4dn.4xlarge
    AllowedValues:
      - g4dn.xlarge
      - g4dn.2xlarge
      - g4dn.4xlarge
      - g4dn.8xlarge
      - g4dn.16xlarge
      - g4dn.12xlarge
  KeyPairName:
    Description: >-
      Public/private key pairs allow you to securely connect to your instance
      after it launches
    Type: AWS::EC2::KeyPair::KeyName
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1 located in Availability Zone 1
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 2 located in Availability Zone 2
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone
      1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR Block for the public DMZ subnet 2 located in Availability Zone
      2
    Type: String
  CloudFormationBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: >-
      CloudFormation assets bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: my-cfn-bucket
    Description: >-
      S3 bucket name for the CloudFormation assets. The bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  CloudFormationKeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: CloudFormation assets key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: my-cfn-key/
    Description: S3 key prefix for the CloudFormation assets. The key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC
    Type: String
  Project:
    Description: Tag used for billing and resource groups
    Type: String
    Default: cloud-video-edit-fsx
  FileSystemSize:
    Description: The storage capacity of the file system being created. 32 GiB - 65,536 GiB (64 TiB)
    Type: Number
    Default: 1024
    MinValue: 32
    MaxValue: 65536
  FSxThroughput:
    Description: >-
      The throughput capacity of an Amazon FSx file system, measured in megabytes per second 
      in powers of 2 (8, 16, 32, ... , 1024), with the recommended value based on the file 
      system size: 8 for <800 GiB, 16 for <1600 GiB, ... 512 for <51200 GiB, 1024 for >=51200 GiB
    Type: Number
    Default: 16
    AllowedValues:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
      - 2048
  AZDeploymentMode:
    Description: 'Specifies the file system deployment type'
    Type: String
    Default: SINGLE_AZ_2
    AllowedValues:
      - SINGLE_AZ_2
      - MULTI_AZ_1

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template'
      Parameters:
        AvailabilityZones: !Join
          - ','
          - !Ref 'AvailabilityZones'
        KeyPairName: !Ref 'KeyPairName'
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref 'PrivateSubnet1CIDR'
        PrivateSubnet2ACIDR: !Ref 'PrivateSubnet2CIDR'
        PublicSubnet1CIDR: !Ref 'PublicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'PublicSubnet2CIDR'
        VPCCIDR: !Ref 'VPCCIDR'
  HostSecGrpStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.${AWS::Region}.${AWS::URLSuffix}/${CloudFormationKeyPrefix}templates/cloud-video-editing-host-security-group.yaml'
      Parameters:
        HostAccessCIDR: !Ref 'EditHostAccessCIDR'
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
  ADStack:
    DependsOn: HostSecGrpStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}submodules/quickstart-microsoft-activedirectory/templates/ad-3.template'
      Parameters:
        DomainAdminPassword: !Ref 'DomainAdminPassword'
        DomainDNSName: !Ref 'DomainDNSName'
        DomainNetBIOSName: !Ref 'DomainNetBIOSName'
        PrivateSubnet1CIDR: !Ref 'PrivateSubnet1CIDR'
        PrivateSubnet1ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
        PrivateSubnet2CIDR: !Ref 'PrivateSubnet2CIDR'
        PrivateSubnet2ID: !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
        PublicSubnet1CIDR: !Ref 'PublicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'PublicSubnet2CIDR'
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
  CloudVideoEditingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}templates/cloud-video-editing-edit-host.yaml'
      Parameters:
        DomainAdminPassword: !Ref 'DomainAdminPassword'
        DomainAdminUser: !Ref 'DomainAdminUser'
        DomainDNSName: !Ref 'DomainDNSName'
        DomainNetBIOSName: !Ref 'DomainNetBIOSName'
        InstanceType: !Ref 'EditHostInstanceType'
        KeyPairName: !Ref 'KeyPairName'
        HostSubnetId: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        FSxNetworkFileShare: !GetAtt 'FSXDNSNameStack.Outputs.FSxNetworkShare'
        SGWNetworkFileShare: 'NONE'
        CloudFormationBucketName: !Ref 'CloudFormationBucketName'
        CloudFormationKeyPrefix: !Ref 'CloudFormationKeyPrefix'
        ExistingHostSecurityGroupID: !GetAtt 'HostSecGrpStack.Outputs.EditInstanceSG'
  FSXGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}templates/cloud-video-editing-fsx-filesystem.yaml'
      Parameters:
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
        DirectoryId: !GetAtt 'ADStack.Outputs.DirectoryId'
        FileSystemSize: !Ref FileSystemSize
        FSxThroughput: !Ref FSxThroughput
        AZDeploymentMode: !Ref AZDeploymentMode
        PrimarySubnetAccess: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
        SecondarySubnetAccess: !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
        Project: !Ref Project
        DomainMemberSGID: !GetAtt 'ADStack.Outputs.DomainMemberSGID'
        HostAccessSGID: !GetAtt 'HostSecGrpStack.Outputs.EditInstanceSG'
  FSXDNSNameStack:
    DependsOn: FSXGatewayStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}templates/cloud-video-editing-fsx-dns-name.yaml'
      Parameters:
        Project: !Ref Project
        CloudFormationBucketName: !Ref CloudFormationBucketName
        LambdaFunctionS3Key: !Sub '${CloudFormationKeyPrefix}sgw/fsx-dns-name.zip'
        Boto3LayerS3Key: !Sub '${CloudFormationKeyPrefix}sgw/boto3-layer.zip'
        FSxFileSystemID: !GetAtt 'FSXGatewayStack.Outputs.FSxFileSystem'

Outputs:
  VPCID: 
    Value: !GetAtt 'VPCStack.Outputs.VPCID'
    Description: ID of the VPC just created
  PrimaryPrivateSubnetID:
    Value: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
    Description: Primary Private Subnet for VPC Created
  SecondaryPrivateSubnetID:
    Value: !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
    Description: Secondary Private Subnet for VPC Created
  PrimaryPublicSubnetID:
    Value: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
    Description: Primary Public Subnet for VPC Created
  SecondaryPublicSubnetID:
    Value: !GetAtt 'VPCStack.Outputs.PublicSubnet2ID'
    Description: Secondary Public Subnet for VPC Created
  HostSecurityGroupID:
    Value: !GetAtt 'HostSecGrpStack.Outputs.EditInstanceSG'
    Description: Host Security Group ID - for controlling ingress into remote edit host
  DomainMemberSGID:
    Value: !GetAtt 'ADStack.Outputs.DomainMemberSGID'
    Description: AD Domain Members Security Group ID
  DirectoryID:
    Value: !GetAtt 'ADStack.Outputs.DirectoryId'
    Description: Microsoft Active Directory ID
  EditHostInstanceID:
    Value: !GetAtt 'CloudVideoEditingStack.Outputs.InstanceId'
    Description: InstanceId of the newly created EC2 instance
  FSXSecurityGroup:
    Value: !GetAtt 'FSXGatewayStack.Outputs.FSXSecurityGroup'
    Description: Security group for the FSX FileSystem created
  FSxFileSystem:
    Value: !GetAtt 'FSXGatewayStack.Outputs.FSxFileSystem'
    Description: The FSX FileSystem Created    
  FSxNetworkShare:
    Description: The Network Share Mapping for the FSX FileSystem Created
    Value: !GetAtt FSXDNSNameStack.Outputs.FSxNetworkShare